// =============================================================================
// Seed data for the Meet Champion demo. Real footballers/coaches with real
// ages (as of Feb 2026) and public-domain photos from Wikimedia Commons.
// =============================================================================
import type { Champion, User } from "./index";

export const SEED_USERS: User[] = [
  {
    id: "user-fan",
    email: "fan@meetchampion.local",
    password: "demo1234",
    displayName: "Alex Fan",
    role: "fan",
    themePresetId: "default",
  },
  {
    id: "user-admin",
    email: "admin@meetchampion.local",
    password: "admin1234",
    displayName: "Admin",
    role: "admin",
  },
];

export const SEED_CHAMPIONS: Champion[] = [
  {
    id: "champ-cr7",
    name: "Cristiano Ronaldo",
    age: 41,
    team: "Al-Nassr",
    category: "celebrity",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8c/Cristiano_Ronaldo_2018.jpg",
    bio: "Cinque-volte Pallone d'Oro. Attaccante iconico, ora al Al-Nassr in Saudi Pro League. Il suo mindset da campione ha ridefinito la longevità nel calcio moderno.",
    ratePerCallCents: 49900,
    callDurationMinutes: 15,
    languages: ["PT", "EN", "ES"],
    countryFlag: "PT",
    services: ["1:1 masterclass", "Career mentoring", "Video autograph"],
    career: [
      { years: "2002-2003", team: "Sporting CP", number: 28 },
      { years: "2003-2009", team: "Manchester United", number: 7 },
      { years: "2009-2018", team: "Real Madrid", number: 7 },
      { years: "2018-2021", team: "Juventus", number: 7 },
      { years: "2021-2022", team: "Manchester United", number: 7 },
      { years: "2023-", team: "Al-Nassr", number: 7 },
    ],
    verified: true,
    ratingAvg: 4.9,
    ratingCount: 812,
    totalCalls: 1284,
  },
  {
    id: "champ-messi",
    name: "Lionel Messi",
    age: 38,
    team: "Inter Miami",
    category: "celebrity",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c1/Lionel_Messi_20180626.jpg",
    bio: "Otto Palloni d'Oro. Considerato uno dei più grandi di sempre. Campione del mondo 2022 con l'Argentina, ora conduce l'Inter Miami in MLS.",
    ratePerCallCents: 49900,
    callDurationMinutes: 15,
    languages: ["ES", "EN"],
    countryFlag: "AR",
    services: ["1:1 masterclass", "Freekick tips", "Career mentoring"],
    career: [
      { years: "2004-2021", team: "FC Barcelona", number: 10 },
      { years: "2021-2023", team: "PSG", number: 30 },
      { years: "2023-", team: "Inter Miami", number: 10 },
    ],
    verified: true,
    ratingAvg: 5.0,
    ratingCount: 954,
    totalCalls: 1501,
  },
  {
    id: "champ-mbappe",
    name: "Kylian Mbappé",
    age: 27,
    team: "Real Madrid",
    category: "celebrity",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e5/Kylian_Mbapp%C3%A9_2018.jpg",
    bio: "Attaccante francese, capitano della Nazionale. Passato al Real Madrid nel 2024. Campione del mondo 2018.",
    ratePerCallCents: 39900,
    callDurationMinutes: 20,
    languages: ["FR", "EN", "ES"],
    countryFlag: "FR",
    services: ["1:1 masterclass", "Speed drills", "Q&A"],
    career: [
      { years: "2015-2017", team: "AS Monaco", number: 29 },
      { years: "2017-2024", team: "Paris Saint-Germain", number: 7 },
      { years: "2024-", team: "Real Madrid", number: 9 },
    ],
    verified: true,
    ratingAvg: 4.9,
    ratingCount: 612,
    totalCalls: 890,
  },
  {
    id: "champ-haaland",
    name: "Erling Haaland",
    age: 25,
    team: "Manchester City",
    category: "athlete",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/0/07/Erling_Haaland_2023_%28cropped%29.jpg",
    bio: "Bomber norvegese del Manchester City. Capocannoniere della Premier League. Fisicalità e freddezza sotto porta al top mondiale.",
    ratePerCallCents: 34900,
    callDurationMinutes: 20,
    languages: ["NO", "EN"],
    countryFlag: "NO",
    services: ["Striker mindset", "Gym & nutrition", "Q&A"],
    career: [
      { years: "2017-2019", team: "Molde", number: 9 },
      { years: "2019-2020", team: "RB Salzburg", number: 9 },
      { years: "2020-2022", team: "Borussia Dortmund", number: 9 },
      { years: "2022-", team: "Manchester City", number: 9 },
    ],
    verified: true,
    ratingAvg: 4.9,
    ratingCount: 428,
    totalCalls: 612,
  },
  {
    id: "champ-bellingham",
    name: "Jude Bellingham",
    age: 22,
    team: "Real Madrid",
    category: "athlete",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/2/23/Jude_Bellingham_England_v_Ghana_23_June_2026-061_%28cropped%29.jpg",
    bio: "Centrocampista inglese, stella del Real Madrid e della Nazionale. Leadership rara per la sua età.",
    ratePerCallCents: 27900,
    callDurationMinutes: 20,
    languages: ["EN", "ES"],
    countryFlag: "EN",
    services: ["Midfield masterclass", "Mentality talk", "Q&A"],
    career: [
      { years: "2019-2020", team: "Birmingham City", number: 22 },
      { years: "2020-2023", team: "Borussia Dortmund", number: 22 },
      { years: "2023-", team: "Real Madrid", number: 5 },
    ],
    verified: true,
    ratingAvg: 4.8,
    ratingCount: 287,
    totalCalls: 340,
  },
  {
    id: "champ-guardiola",
    name: "Pep Guardiola",
    age: 55,
    team: "Manchester City",
    category: "coach",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Pep_Guardiola.jpg",
    bio: "Il più influente allenatore della sua generazione. 3x Champions League, tiki-taka, positional play. Consulente e formatore d'eccellenza.",
    ratePerCallCents: 59900,
    callDurationMinutes: 45,
    languages: ["ES", "CA", "EN"],
    countryFlag: "ES",
    services: ["Tactics deep dive", "Team building", "Consulting"],
    career: [
      { years: "2008-2012", team: "FC Barcelona (Head Coach)" },
      { years: "2013-2016", team: "Bayern Munich (Head Coach)" },
      { years: "2016-", team: "Manchester City (Head Coach)" },
    ],
    verified: true,
    ratingAvg: 5.0,
    ratingCount: 512,
    totalCalls: 620,
  },
  {
    id: "champ-ancelotti",
    name: "Carlo Ancelotti",
    age: 66,
    team: "Brazil NT",
    category: "coach",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e9/Carlo_Ancelotti_Brazil_V_Morocco_13_June_2026-34.jpg",
    bio: "Unico allenatore ad aver vinto in tutti i top 5 campionati europei. 5x Champions League. Ora CT del Brasile.",
    ratePerCallCents: 54900,
    callDurationMinutes: 45,
    languages: ["IT", "EN", "ES"],
    countryFlag: "IT",
    services: ["Man management", "Big match preparation", "Consulting"],
    career: [
      { years: "2001-2009", team: "AC Milan (Head Coach)" },
      { years: "2009-2011", team: "Chelsea (Head Coach)" },
      { years: "2013-2015", team: "Real Madrid (Head Coach)" },
      { years: "2016-2017", team: "Bayern Munich (Head Coach)" },
      { years: "2019-2021", team: "Everton (Head Coach)" },
      { years: "2021-2025", team: "Real Madrid (Head Coach)" },
      { years: "2025-", team: "Brazil NT (Head Coach)" },
    ],
    verified: true,
    ratingAvg: 4.9,
    ratingCount: 640,
    totalCalls: 785,
  },
  {
    id: "champ-vieri",
    name: "Christian Vieri",
    age: 52,
    team: "Ex Inter · Retired",
    category: "expert",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Christian_Vieri.jpg/600px-Christian_Vieri.jpg",
    bio: "Ex bomber dell'Italia e dell'Inter. Oggi commentatore e appassionato divulgatore. Racconta storie di spogliatoio e mentalità da centravanti.",
    ratePerCallCents: 12900,
    callDurationMinutes: 30,
    languages: ["IT", "EN"],
    countryFlag: "IT",
    services: ["Storie da bomber", "Mentalità competitiva", "Q&A"],
    career: [
      { years: "1996-1997", team: "Atlético Madrid", number: 9 },
      { years: "1997-1998", team: "Lazio", number: 32 },
      { years: "1999-2005", team: "Inter", number: 32 },
      { years: "2005-2006", team: "AC Milan", number: 11 },
    ],
    verified: true,
    ratingAvg: 4.8,
    ratingCount: 156,
    totalCalls: 220,
  },
];
